### ISSUE TITLE
关于setting.json文件的询问

### ISSUE THREAD

**Issue by Phigent** [jzstudent/UAV-auto-navigation-and-object-tracking-based-on-RL#2]
请问大佬，在Aisim中是怎么进行配置的呢，如何做到自定义方针环境？

**Comment by jzstudent** [comment]
> 请问大佬，在Aisim中是怎么进行配置的呢，如何做到自定义方针环境？

自定义环境需要搭建ue4需要的物理模型和环境，Aisrim提供了几个已经配置好的环境，也可以去UE4仓库拉几个免费的使用。Airsim的setting配置去看他官方的doc就行，很详细

**Comment by Phigent** [comment]
好的，谢谢
